# Generated by Django 2.2.5 on 2019-09-25 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from web.models import Topic

Topic.objects.get_or_create(title="Science")
Topic.objects.get_or_create(title="Computers")
Topic.objects.get_or_create(title="Cats")
Topic.objects.get_or_create(title="Dogs")
Topic.objects.get_or_create(title="IoT")
Topic.objects.get_or_create(title="Internet")



class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(default='web/templates/default.jpg', upload_to='media')),
                ('bio', models.CharField(max_length=256, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
